### ISSUE TITLE
Stack instructions not complete

### ISSUE THREAD

**Issue by houshuang** [wereHamster/nauva#19]
I tried following the readme instructions 

```
git clone https://github.com/wereHamster/navua.git
cd nauva
./bin/dev playground/app
```

however, it complained that I did not have GHC 8.0.2 (apparently I had 8.0.1), and doing `stack setup` from the root directory did not work, because it could not see the stack.yaml file. Going to `hs/nauvad` and running `stack setup` correctly downloaded GHC 8.0.2.

**Comment by wereHamster** [comment]
Should be fixed with 727ac2f (bin/dev: install GHC if required, 2017-03-30).
